version: "3.8"
services:
  django:
    build: .
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - ALLOWED_HOSTS=localhost, 127.0.0.1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      # - db
    volumes:
      - .:/usr/src/app

  celery:
    build: .
    container_name: celery_container
    command: celery -A scraper worker -l INFO
    depends_on:
      - django
      - redis
    volumes:
      - .:/usr/src/app

  redis:
    image: redis:alpine
    container_name: redis_container
    # ports:
    #   - "6379:6379"
